<?php $this->headTitle()->append('@asgrim'); ?>

<div class="pull-right">
    <p>
        <img src="/images/photo.png" alt="Photo of James Titcumb" class="pull-right" style="margin-bottom: 5px;" />
    </p>
    <p>
        <a href="http://www.zend.com/en/yellow-pages/ZEND010150"><img src="/images/zce.png" alt="Zend Certified Engineer PHP 5.3" /></a>
        <a href="http://www.zend.com/en/yellow-pages/ZEND010150"><img src="/images/zcpe.png" alt="Zend Certified PHP Engineer" /></a>
        <a href="http://www.zend.com/en/yellow-pages/ZEND010150"><img src="/images/zce-2017.gif" alt="Zend Certified Engineer 2017-PHP" /></a>
    </p>
</div>

<h2>Who am I?</h2>

<p>Hi there! I'm James Titcumb. I've been a PHP developer since 2002. Here's some facts about me:</p>

<ul>
    <li>I am a freelance consultant developer under the <a href="http://www.roave.com/">Roave</a> team banner, where I work with an <em>amazing</em> team of developers.</li>
    <li>I am a <a href="http://www.zend.com/en/yellow-pages/ZEND010150">Zend Certified PHP Engineer</a>.</li>
    <li>I run the <a href="http://www.phpsouthcoast.co.uk/">PHP South Coast</a> conference.</li>
    <li>I run the <a href="http://www.phphants.co.uk/">PHP Hampshire</a> PHP user group.</li>
    <li>I speak as much as I can at user groups and conferences; <a href="/talks">see all the talks I'm doing and have done</a>.</li>
    <li>I love contributing to <a href="https://github.com/asgrim">open source software</a>, such as Zend Framework, Zend Expressive, Doctrine and more.</li>
    <li>I am the project lead for Roave's <a href="https://github.com/Roave/BetterReflection">Better Reflection</a> library.</li>
    <li>I am the project lead for the <a href="https://github.com/browscap/browscap">Browser Capabilities Project</a>.</li>
    <li>I live in <a href="http://en.wikipedia.org/wiki/Portsmouth">Portsmouth, UK</a> and I'm married, with 2 children.</li>
    <li>I have written three articles for php[architect] magazine (<a href="http://www.phparch.com/magazine/2015-2/april/">Apr 2015</a>, <a href="https://www.phparch.com/magazine/2015-2/november/">Nov 2015</a>, <a href="https://www.phparch.com/magazine/2017-2/january/">Jan 2017</a>)</li>
    <li>I was a technical editor for <a href="https://leanpub.com/im_british_so_i_know_how_to_queue">I'm British So I Know How to Queue</a>, a RabbitMQ book by <a href="https://twitter.com/stubbs">Stuart Grimshaw</a>.</li>
</ul>

<h2>Hire me!</h2>

<p>As a professional PHP consultant with many years of experience, I can offer many consultancy services to clients, including:</p>

<ul>
    <li>Mentoring and training</li>
    <li>Consultancy and advice</li>
    <li>Software and application development</li>
    <li>Refactoring expertise and consulting</li>
    <li>Project planning and scoping</li>
    <li>Code reviews and quality</li>
</ul>

<h2>Get in touch...</h2>

<p>You can get in touch with me the following ways:</p>

<ul>
    <li>Twitter: <a href="https://twitter.com/asgrim">@asgrim</a></li>
    <li>GitHub: <a href="https://github.com/asgrim">github.com/asgrim</a></li>
    <li>LinkedIn: <a href="https://uk.linkedin.com/in/jamestitcumb">uk.linkedin.com/in/jamestitcumb</a></li>
    <li>Google+: <a href="https://plus.google.com/115315299682874378471">James Titcumb</a></li>
    <li>IRC (freenode): asgrim</li>
</ul>
