<?php

declare(strict_types=1);

use Asgrim\Value\Post;

/**
 * @var Post[] $posts
 * @var string $title
 */

$this->headTitle()->append($title);
$blogPostMarketing = $this->partial('partial::blog-post-marketing');
?>

<?php foreach ($posts as $post): ?>
<article style="margin-bottom: 60px;">
	<div class="article-header">
		<h1><a href="<?= $this->url('posts', ['slug' => $post->slug()]); ?>"><?= $this->escapeHtml($post->title()); ?></a></h1>
		<p class="article-meta">
			Posted on <?= $post->date()->format('jS F Y'); ?>
		</p>
	</div>
	<hr />
	<div class="article-body">
		<?= str_replace('<!-- MARKETING -->', $blogPostMarketing, $this->renderPostContent($post->slug())) ?>
	</div>

	<?php if ($post->shouldShowComments()): ?>
		<hr />
	<?php endif; ?>

</article>
<?php endforeach; ?>
