<?php

declare(strict_types=1);

use Asgrim\Value\Post;

/**
 * @var Post[] $posts
 * @var string $title
 */

$this->headTitle()->append($title);
?>

<?php foreach ($posts as $post): ?>
<article style="margin-bottom: 60px;">
	<div class="article-header">
		<h1><a href="<?= $this->url('posts', ['slug' => $post->slug()]); ?>"><?= $this->escapeHtml($post->title()); ?></a></h1>
		<p style="font-weight: bold; font-style: italic;">
			Posted on <?= $post->date()->format('jS F Y'); ?>
			| <a href="<?= $this->url('posts', ['slug' => $post->slug()]); ?>#disqus_thread" data-disqus-identifier="<?= $this->escapeHtmlAttr($post->slug()); ?>">View comments</a>
		</p>
	</div>
	<hr />
	<div class="article-body">
		<?php echo $this->renderPostContent($post->slug()); ?>
	</div>

	<?php if ($post->shouldShowComments()): ?>
		<hr />

		<div id="disqus_thread"></div>
		<script type="text/javascript">
			/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
			var disqus_shortname = 'asgrim'; // required: replace example with your forum shortname
			var disqus_identifier = '<?= $this->escapeHtml($post->slug()); ?>';
			//var disqus_title = '<?= $this->escapeHtml($post->title()); ?>';
			var disqus_title = '/posts/<?= $this->escapeHtml($post->slug()); ?>';

			/* * * DON'T EDIT BELOW THIS LINE * * */
			(function() {
				var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
				dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
				(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
			})();
		</script>
		<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
		<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
	<?php endif; ?>

</article>
<?php endforeach; ?>
