<?php

declare(strict_types=1);

use Asgrim\Value\Talk;

/** @var Talk[] $upcoming */
/** @var Talk[] $past */

$this->headTitle()->append('Upcoming talks');
?>

<h1>Talks</h1>

<h2>Upcoming talks</h2>

<?php
if (count($upcoming)) {
    echo '<ul class="talk-list">';
    foreach ($upcoming as $t) {
        echo $this->renderTalk($t);
    }
    echo '</ul>';
} else {
    echo '<p>No upcoming talks&hellip; check back soon!</p>';
}
?>

<hr />

<h2>Past talks</h2>
<p class="talk-list__count">I have given <?= count($past); ?> talks in the past:</p>

<?php
echo '<ul class="talk-list talk-list--past">';
foreach ($past as $t) {
    echo $this->renderTalk($t, skipAbstract: true);
}
echo '</ul>';
?>
