<?php
$this->headTitle()->append('Upcoming talks');
$this->headScript()->appendFile('//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js');
$this->headScript()->appendFile('/js/joindin-ratings.min.js');
?>

<p>Upcoming talks:</p>

<?php
if (count($upcoming)) {
    echo '<ul>';
    foreach ($upcoming as $t) {
        echo $this->renderTalk($t);
    }
    echo '</ul>';
} else {
    echo '<p>No upcoming talks...</p>';
}
?>

<p>This is a list of talks I've given:</p>

<?php
echo '<ul>';
foreach ($past as $t) {
    echo $this->renderTalk($t);
}
echo '</ul>';
?>
