<?php
declare(strict_types=1);
$this->headTitle()->append('Training and Workshops');
?>

<h2>Training &amp; Workshops</h2>

<p>
I can provide bespoke training and workshops for your company. The training sessions can be done on site, or remotely
via video chat and screen sharing.
</p>

<h4>Potential topics that can be included</h4>

<ul>
    <li>PHP fundamentals &amp; modern best practices</li>
    <li>Continuous Integration with Jenkins and/or Travis</li>
    <li>Behaviour Driven Design with Behat</li>
    <li>Unit testing with PHPUnit</li>
    <li>Refactoring legacy code</li>
    <li>Software Development Lifecycle improvements</li>
    <li>Deployment strategies and automation</li>
    <li>Domain Driven Design</li>
    <li>CQRS and Event Sourcing</li>
    <li>... and more! Just ask.</li>
</ul>

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">I can help you improve your business.</h3>
    </div>
    <div class="panel-body">
        <p>If you'd like me to help your PHP software developers improve, get in touch today:</p>
        <?= $this->partial('partial::contact'); ?>
    </div>
</div>
