<?php
declare(strict_types=1);
$this->headTitle()->append('Training and Workshops');
?>

<h2>Training &amp; Workshops</h2>

<p>
I can provide bespoke training and workshops for your company. The training sessions can be done on site, or remotely
via video chat and screen sharing.
</p>

<h3>Potential topics that can be included</h3>

<ul>
    <li>PHP fundamentals &amp; modern best practices</li>
    <li>Continuous Integration with GitHub Actions, Gitlab Pipelines, and more</li>
    <li>Behaviour Driven Design with Behat</li>
    <li>Unit testing with PHPUnit</li>
    <li>Refactoring legacy code</li>
    <li>Software Development Lifecycle improvements</li>
    <li>Deployment strategies and automation</li>
    <li>Domain Driven Design</li>
    <li>CQRS and Event Sourcing</li>
    <li>... and more! Just ask.</li>
</ul>

<h3>Consulting &amp; Advice</h3>

<p>
On top of training and workshops, I can help you with consulting for your development team, covering a wide range of
subject matters. Get in touch with me today to find out more.
</p>


