<?php
declare(strict_types=1);
$this->headTitle()->append('Training and Workshops');
?>

<h2>Training &amp; Workshops</h2>

<p>
I can provide bespoke training and workshops for your company. The training sessions can be done on site, or remotely
via video chat and screen sharing.
</p>

<h3>Potential topics that can be included</h3>

<ul>
    <li>PHP fundamentals &amp; modern best practices</li>
    <li>Continuous Integration with Jenkins and/or Travis</li>
    <li>Behaviour Driven Design with Behat</li>
    <li>Unit testing with PHPUnit</li>
    <li>Refactoring legacy code</li>
    <li>Software Development Lifecycle improvements</li>
    <li>Deployment strategies and automation</li>
    <li>Domain Driven Design</li>
    <li>CQRS and Event Sourcing</li>
    <li>... and more! Just ask.</li>
</ul>

<h3>Consulting &amp; Advice</h3>

<p>
On top of training and workshops, I can help you with consulting for your development team, covering a wide range of
subject matters. Get in touch with me today to find out more.
</p>

<h3>Testimonials</h3>

<blockquote>
    As founder of a consulting group trusted to provide expert PHP and IBM i solutions and guidance, I gladly turn to
    James whenever we need additional PHP and Zend Framework expertise. His years of experience, positive attitude, and
    proficiency with technical structure and back-end development make him a pleasure to work with. What's more, he's a
    really nice guy. Every project goes better with James.
</blockquote>
<blockquote>
    James is a developer with great experience that will find a simple and elegant solution of any problem. He is
    resourceful and he would be of great help to any business in finding what works best for them. A development team
    will benefit from his expertise for high standards of software development and architecture. Working with him was a
    pleasure and I would be happy to be in his team again.
</blockquote>
<blockquote>
    James is one of the most passionate and talented programmer I've ever met. He cares deeply about solving the right
    problem with the right tools, and his knowledge of PHP and related technologies is impressive.
</blockquote>
<blockquote>
    James is by far and away the most talented developer I have ever met. He can not only code but understands why he
    is coding - his understanding of the business requirement is amazing.
</blockquote>
<blockquote>
    James is a very technical developer with good problem solving abilities, able to think outside the box to design
    and find solutions. James used his knowledge to provide additional support and contributions to other areas of the
    company.
</blockquote>
<blockquote>
    James is a very technically gifted guy, who can solve a lot of issues others are struggling with. He can always be
    relied on to solve problems to a very high standard, and his estimates are always spot on. Great guy to work with.
</blockquote>

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">I can help you improve your PHP team.</h3>
    </div>
    <div class="panel-body">
        <p>If you'd like me to help your PHP software developers improve, get in touch today:</p>
        <?= $this->partial('partial::contact'); ?>
    </div>
</div>
