language: php
sudo: required

services:
  - elasticsearch

php:
  - 7.0

before_script:
  - sleep 10
  - composer install --dev

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml --colors

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover clover.xml
