language: php
sudo: false

php:
  - 5.5

before_script:
  - composer install --dev

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml --colors

after_script:
  - if [ $TRAVIS_PHP_VERSION = '5.5' ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi

matrix:
  allow_failures:
     - php: hhvm
