language: php
sudo: false

services:
  - elasticsearch

php:
  - 7.4

before_script:
  - sleep 10
  - cp config/autoload/local.php.travis config/autoload/local.php
  - composer install

script:
  - vendor/bin/phpunit --coverage-text --colors
  - vendor/bin/phpcs
  - vendor/bin/psalm
