# These docker-compose definitions are suited for a development environment, not for CI or production-alike systems.
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  elasticsearch:
    image: elasticsearch:7.10.1
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 3s
      retries: 6
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
