<!DOCTYPE html>
<html>
<head>
	<title>James Titcumb</title>

	<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="/css/style.css" media="screen" />
</head>
<body>
	<header>
		<div id="header">
			<h1>James Titcumb</h1>
		</div>

		<nav>
			<ul>
				<li><a href="/">Home</a></li>
				<li><a href="/blog">Blog</a></li>
				<li><a href="/open-source">Open Source</a>
			</ul>
			<div class="clear"></div>
		</nav>
	</header>

	<div id="contentContainer"><div id="content">
		[content]
	</div></div>

	<footer>
		<div id="footer">
			<p>
				<a href="https://www.twitter.com/asgrim">Twitter</a> |
				<a href="https://github.com/asgrim/">GitHub</a> |
				<a href="https://plus.google.com/115315299682874378471/posts">Google+</a>
			</p>
			<p>&copy; Copyright 2013 James Titcumb &mdash; Source on <a href="https://github.com/asgrim/jamestitcumb">GitHub</a>!</p>
		</div>
	</footer>
</body>
</html>