
<h1>Ahoy there!</h1>

<p>Here's what I'm about:</p>

<ul>
	<li>I'm a full-time PHP developer at <a href="http://www.ed.co.uk/">The Ed Group</a>.</li>
	<li>I'm also a Zend Certified Engineer PHP 5.3.</li>
	<li>I'm a married homeowner, father of one, and a dog owner.</li>
	<li>I contribute to open source software as much as I can.</li>
	<li>I help organise <a href="http://www.phphants.co.uk/">PHP Hampshire</a>, a PHP User Group.</li>
	<li>Occasionally I play video games. I am useless at all of them.</li>
</ul>
