
<div id="openSource">

	<div id="phphants" class="card"><div class="inner">
		<img src="/images/phphants.png" />
		<h3>PHP Hampshire</h3>
		<p>With a fellow PHP developer I started the PHP Hants PHP User Group which I aim to cover Hampshire and bring together like-minded PHP developers in the community. Through this I am trying to encourage developers to contribute back to open source software.</p>
		<p><a href="http://www.phphants.co.uk/">www.phphants.co.uk</a> </p>
	</div></div>

	<div id="godeploy" class="card"><div class="inner">
		<img src="/images/godeploy.png" />
		<h3>GoDeploy</h3>
		<p>We created GoDeploy to automate our deployments. It just takes a Git repository and deploys it to specified a specified FTP server. It's written in PHP and designed to be installed on your own server.</p>
		<p><a href="http://www.godeploy.com/">www.godeploy.com</a> </p>
	</div></div>

	<div id="github" class="card"><div class="inner">
		<img src="/images/octocat.png" />
		<h3>I'm on GitHub</h3>
		<p>Find me on <a href="https://github.com/asgrim">GitHub</a>, or have a look at my <a href="http://resume.github.io/?asgrim">GitHub R&eacute;sum&eacute;</a>. Here's some stuff I've written in the past:</p>
		<ul>
			<li><a href="https://github.com/asgrim/ofxparser">OFX Parser</a> <cite>(PHP)</cite></li>
			<li><a href="https://github.com/asgrim/jamestitcumb">This website!</a> <cite>(PHP)</cite></li>
			<li><a href="https://github.com/asgrim/zdt-memcache">ZDT Memcached</a> <cite>(ZF2)</cite></li>
			<li><a href="https://github.com/asgrim/directory-syncing-thing">Directory Syncing Thing</a> <cite>(Bash)</cite></li>
			<li><a href="https://github.com/asgrim/zfhtml5">ZF1 HTML5 Boilerplate</a> <cite>(ZF1)</cite></li>
		</ul>
	</div></div>

	<div class="clear"></div>
</div>
