<div class="panel panel-primary" style="background-color: #edf6fa;">
    <div class="panel-body">
        <p class="lead">
            Need some help? I specialise in helping development teams to write high quality PHP applications.

        <p>
            Get in touch with me to see how I can start helping your team today:
        </p>
        <?= $this->partial('partial::contact') ?>
    </div>
</div>
