<ul>
    <li>Email: <a href="mailto:hello@jamestitcumb.com">hello@jamestitcumb.com</a></li>
    <li>Twitter: <a href="https://twitter.com/asgrim">@asgrim</a></li>
    <li>GitHub: <a href="https://github.com/asgrim">github.com/asgrim</a></li>
    <li>LinkedIn: <a href="https://uk.linkedin.com/in/jamestitcumb">uk.linkedin.com/in/jamestitcumb</a></li>
    <li>Calendly: <!-- Calendly link widget begin -->
<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
<a href="https://calendly.com/asgrim/30min" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/asgrim/30min'});return false;">Schedule a call with me</a>
<!-- Calendly link widget end --></li>
</ul>
