<ul>
    <li>Email: <a href="mailto:hello@jamestitcumb.com">hello@jamestitcumb.com</a></li>
    <li>Twitter: <a href="https://twitter.com/asgrim">@asgrim</a></li>
    <li>GitHub: <a href="https://github.com/asgrim">github.com/asgrim</a></li>
    <li>LinkedIn: <a href="https://uk.linkedin.com/in/jamestitcumb">uk.linkedin.com/in/jamestitcumb</a></li>
    <li>Mastodon: <a href="https://phpc.social/@asgrim">@asgrim@phpc.social</a></li>
</ul>
