<!DOCTYPE html>
<html lang="en">
<head>
    <title>James Titcumb</title>
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link rel="alternate" type="application/rss+xml" title="James Titcumb's blog feed" href="http://www.jamestitcumb.com/feed" />
    <?php echo $this->headScript() ?>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><strong>James Titcumb</strong></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">About Me</a></li>
                <li><a href="/posts">Posts</a></li>
                <li><a href="/talks">Talks</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">

    <?= $this->content; ?>

</div>

<hr />
<footer class="text-center" style="font-size: 80%;">
    <p>&copy; Copyright <?php echo date('Y'); ?>, JT Web Development Ltd, registered in England &amp; Wales, company number 09588091, VAT number 215 351 636</p>
</footer>

<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-3367595-5']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>

<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'asgrim'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>

</body>
</html>
