name: QA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  qa:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure application
        run: cp config/autoload/local.php.dist config/autoload/local.php

      - name: Build and pull images
        run: |
          docker compose build
          docker compose pull

      - name: Run tests
        run: |
          docker compose run --rm web vendor/bin/phpunit --do-not-cache-result

      - name: Run static analysis check
        run: |
          docker compose run --rm --no-deps web vendor/bin/psalm

      - name: Check code style
        run: |
          docker compose run --rm --no-deps web vendor/bin/phpcs --no-cache
